---
exclude_paths:
  - 'docs/**'
  - 'river_admin/migrations/*'
  - 'river_admin/templates/**'
  - 'river_admin/static/**'
  - 'river_admin_shipping_example/**'
  - 'river_admin_issue_tracker_example/**'
  - 'river_admin_demo/**'
  - 'test_settings.py'
  - 'manage.py'
  - 'test_urls.py'
  - 'setup.py'
  - '**/tests/**'