---
exclude_paths:
  - 'docs/**'
  - 'river_admin/migrations/*'
  - 'river_admin/templates/**'
  - 'river_admin/static/**'
  - 'examples/**'
  - 'demo/**'
  - 'local_settings.py'
  - 'manage.py'
  - 'local_urls.py'
  - 'setup.py'
  - '**/tests/**'