---
exclude_paths:
  - 'river-admin/migrations/*'
  - 'river-admin/templates/*'
  - 'river-admin/static/*'
  - 'river_admin_shipping_example/*'
  - 'river_admin_issue_tracker_example/*'
  - '**/tests/**'