---
exclude_paths:
  - 'docs/*'
  - 'river_admin/migrations/*'
  - 'river_admin/templates/*'
  - 'river_admin/static/*'
  - 'river_admin_shipping_example/*'
  - 'river_admin_issue_tracker_example/*'
  - 'test_settings'
  - 'manage.py'
  - 'test_urls.py'
  - 'setup.py'
  - '**/tests/**'