---
exclude_paths:
  - 'docs/**'
  - 'river_admin/migrations/*'
  - 'river_admin/templates/**'
  - 'river_admin/static/**'
  - 'examples/**/**'
  - 'demo/**/**'
  - 'test_settings.py'
  - 'manage.py'
  - 'test_urls.py'
  - 'setup.py'
  - '**/tests/**'